# Taxonomy of supported categories and subcategories for Agent 1

CATEGORIES = {
    "Identity & Civil Registration": [
        "CNIC / Smart CNIC",
        "CNIC Renewal",
        "CNIC Modification / Correction",
        "Lost CNIC",
        "Family Registration Certificate (FRC)",
        "Child Registration Certificate (B-Form/CRC)",
        "Birth Registration",
        "Death Registration",
        "Marriage Registration",
        "Divorce Registration",
        "Domicile / Residence Certificate",
        "Other NADRA Services"
    ],
    "Passport & Immigration": [
        "New Passport",
        "Passport Renewal",
        "Passport Modification",
        "Lost / Damaged Passport",
        "Urgent Passport",
        "Overseas Pakistani Services",
        "Passport Tracking",
        "Visa / Immigration Information",
        "Other Passport Services"
    ],
    "Driving & Vehicle Services": [
        "Learner Driving License",
        "Permanent Driving License",
        "Driving License Renewal",
        "Driving License Conversion",
        "International Driving Permit",
        "Duplicate Driving License",
        "Vehicle Registration",
        "Vehicle Ownership Transfer",
        "Vehicle Verification",
        "Number Plate",
        "Token Tax",
        "Traffic Challan",
        "Other Vehicle Services"
    ],
    "Tax & Finance": [
        "NTN Registration",
        "Income Tax Registration",
        "Income Tax Return",
        "Taxpayer Verification",
        "Sales Tax Registration",
        "Sales Tax Return",
        "Tax Payment",
        "Withholding Tax",
        "Property Tax",
        "Professional Tax",
        "Tax Refund",
        "Other Tax Services"
    ],
    "Business & Company": [
        "Company Registration",
        "Sole Proprietorship",
        "Partnership Registration",
        "Business Registration",
        "SECP Services",
        "Business Tax Registration",
        "Sales Tax Registration",
        "Trademark Registration",
        "Import / Export Registration",
        "Business Licenses / Permits",
        "SME Government Programs",
        "Other Business Services"
    ],
    "Property & Land": [
        "Fard / Land Ownership Record",
        "Land Record Verification",
        "Mutation / Intiqal",
        "Property Transfer",
        "Property Registration",
        "Stamp Duty",
        "Property Tax",
        "Land Ownership Issues",
        "Building Approval",
        "Construction Permission",
        "Land-Use Information",
        "Other Land Services"
    ],
    "Education": [
        "HEC Degree Attestation",
        "Degree Verification",
        "Degree Equivalence",
        "HEC Online Services",
        "Scholarships",
        "Government University Admissions",
        "Educational Certificates",
        "Board / Examination Services",
        "Student Financial Assistance",
        "Teacher-Related Services",
        "Other Education Services"
    ],
    "Employment & Labour": [
        "Government Jobs",
        "Labour Registration",
        "EOBI Services",
        "Social Security",
        "Employee Rights",
        "Minimum Wage Information",
        "Workers' Welfare Programs",
        "Labour Complaints",
        "Workplace Safety",
        "Employment Certificates",
        "Other Labour Services"
    ],
    "Health Services": [
        "Government Hospital Services",
        "Hospital Information",
        "Health Insurance / Government Health Programs",
        "Medical Assistance Programs",
        "Vaccination Information",
        "Public Health Services",
        "Maternal & Child Health",
        "Disability-Related Health Services",
        "Health Complaints",
        "Other Health Services"
    ],
    "Agriculture & Livestock": [
        "Farmer Registration",
        "Agricultural Subsidies",
        "Fertilizer Subsidies",
        "Seed Programs",
        "Agricultural Loans",
        "Crop Insurance",
        "Crop-Related Government Programs",
        "Livestock Programs",
        "Irrigation Services",
        "Agricultural Complaints",
        "Other Agriculture Services"
    ],
    "Local Government & Municipal Services": [
        "Birth / Death Registration",
        "Marriage Registration",
        "Building Permissions",
        "Water & Sewerage Complaints",
        "Waste Management Complaints",
        "Road / Street Complaints",
        "Streetlight Complaints",
        "Sanitation Services",
        "Property / Municipal Tax",
        "Local Certificates",
        "Municipal Complaints",
        "Other Local Government Services"
    ],
    "Utilities": [
        "Electricity New Connection",
        "Electricity Complaint",
        "Electricity Meter Issues",
        "Electricity Bill Issues",
        "Gas New Connection",
        "Gas Complaint",
        "Gas Meter Issues",
        "Gas Bill Issues",
        "Water Connection",
        "Water / Sewerage Complaint",
        "Disconnection / Reconnection",
        "Other Utility Services"
    ],
    "Legal, Police & Public Services": [
        "FIR Registration",
        "FIR Copy / Information",
        "FIR Not Registered",
        "Police Complaint",
        "Police Character Certificate",
        "Police Verification",
        "Tenant Verification",
        "Employee Verification",
        "Lost Document Report",
        "Missing Person / Child Report",
        "Traffic-Related Complaint",
        "Police Misconduct Complaint",
        "Complaint Against Investigation",
        "Government Department Complaint",
        "Pakistan Citizen's Portal",
        "Ombudsman Complaint",
        "Consumer Complaint",
        "Human Rights Complaint",
        "Legal Aid Information",
        "Court Procedure Information",
        "Women / Child Protection Services",
        "Other Legal / Public Services"
    ],
    "Environment & Construction": [
        "Environmental Complaint",
        "Environmental Approval / NOC",
        "EPA Services",
        "Environmental License",
        "Industrial Environmental Approval",
        "Construction Approval",
        "Building Regulations",
        "Construction NOC",
        "Pollution Complaint",
        "Waste / Environmental Issues",
        "Other Environment Services"
    ],
    "Social Welfare & Assistance": [
        "BISP Services",
        "Social Assistance Programs",
        "Zakat Assistance",
        "Financial Assistance",
        "Disability Support",
        "Senior Citizen Programs",
        "Women Support Programs",
        "Child Welfare Services",
        "Orphan Support Programs",
        "Government Relief Programs",
        "Social Welfare Registration",
        "Other Social Welfare Services"
    ],
    "Telecommunication & Internet Services": [
        "SIM Registration / Verification",
        "SIM Ownership / Change of Ownership",
        "Lost / Blocked SIM",
        "SIM Replacement",
        "Number Portability",
        "Mobile Packages",
        "Internet / Data Packages",
        "Call & SMS Packages",
        "Package Activation / Deactivation",
        "Balance / Package Information",
        "Mobile Internet Problems",
        "Broadband / Fiber Internet",
        "New Internet Connection",
        "Internet Package Comparison",
        "PTCL Services",
        "Jazz Services",
        "Zong Services",
        "Ufone Services",
        "Telenor Services",
        "PTA Complaints",
        "Spam / Unwanted Calls & SMS",
        "Other Telecom Services"
    ]
}
